### ISSUE TITLE
[FEATURE] Visually differentiating between "UNKNOWN" and zero/not OSI-approved license, etc.

### ISSUE THREAD

**Issue by magnuspalmblad** [Workflomics/workflomics-frontend#73]
## Feature Description
In the benchmark view, both "UNKNOWN" licenses/number of citations, and non-OSI-approved licenses/zero citations are mapped to white.

## Motivation
It would be nice to be able to be able to visually distinguish between these NAs and zeroes.

## Proposed Solution
Map NAs (unknowns) to a diagonal black line through the small box (white background) and continue to map non-OSI-approved license/zero citations to white.

## Alternatives Considered
No alternatives have been considered.

## Additional Context

**Comment by vedran-kasalica** [comment]
I looked into it, and it's not hard to implement a diagonal line to it. Does this look like something you had in mind? If we decide to use it, we can have all elements that are unknown (number of citations for example) marked the same way

<img width="452" alt="Screenshot 2024-08-12 at 17 11 16" src="https://github.com/user-attachments/assets/f9101c60-6ce1-4520-9be9-97ec8f5e1547">
